### ISSUE TITLE
 rest-clientを使って、APIのレスポンスを取得する

### ISSUE THREAD

**Issue by beppumasaki** [beppumasaki/impersonation_practice#14]
## 質問内容・実現したいこと

rest-clientを使って、APIのレスポンスを取得したい。

## 現状発生している問題・エラーメッセージ

APIのレスポンスを結果画面で表示する機能を実装したいと考えており、HTTPクライアントとしてrest-clientを使っています。
レスポンスの詳細を把握するためデバッグしたところ、
Invalid audio format. Supported format is WAV 16Khz 16bit Mono PCM.というエラーメッセージが表示されています。

```

Started POST "/targets/7/results" for ::1 at 2022-04-07 07:07:10 +0900
Processing by ResultsController#create as JSON
  Parameters: {"target_id"=>"7", "impersonation_voice"=>#<ActionDispatch::Http::UploadedFile:0x000000011490d250 @tempfile=#<Tempfile:/var/folders/yh/f08h6xg929l0cl1gg8y95l600000gn/T/RackMultipart20220407-4546-17it0dm.wav>, @original_filename="voice.wav", @content_type="audio/wav", @headers="Content-Disposition: form-data; name=\"impersonation_voice\"; filename=\"voice.wav\"\r\nContent-Type: audio/wav\r\n">, "score"=>"100"}

[23, 32] in /Users/beppumasaki/workspace/my_app/impersonation_practice/app/controllers/results_controller.rb
   23:         'Transfer-Encoding': 'chunked'
   24:       }
   25:     )
   26:    rescue RestClient::ExceptionWithResponse => e
   27:     byebug
=> 28:     @result = Result.create(result_params)
   29:     render json: { url: target_result_url(@result.target_id, @result.id) }
   30:   end
   31: 
   32:   private
(byebug) e.response.body
"{\"error\":{\"code\":\"InvalidRequest\",\"message\":\"Invalid audio format. Supported format is WAV 16Khz 16bit Mono PCM.\"}}"
(byebug) voice
#<File:/var/folders/yh/f08h6xg929l0cl1gg8y95l600000gn/T/RackMultipart20220407-4546-17it0dm.wav>

```

## どの処理までうまく動いているのか

postmanでは正常に動いています。

![https://i.gyazo.com/49c1871588d40dbc6823eb4e02cfd64d.png](https://i.gyazo.com/49c1871588d40dbc6823eb4e02cfd64d.png)

## 該当のソースコード
results_controller.rb
```

def create
    voice = File.new(params[:impersonation_voice])
    response = RestClient::Request.execute(
      method: :post,
      url: 'https://westus.api.cognitive.microsoft.com/speaker/identification/v2.0/text-independent/profiles/identifySingleSpeaker',
      headers: {
        'Ocp-Apim-Subscription-Key': 'd707afb0596c47968b5e0ed7f263c9be',
        'Content-type': 'audio/wav; codecs=audio/pcm; samplerate=16000',
        params: {
          profileIds: '42408f55-0250-4679-9950-ab72672f3958,305fbca2-be86-49b9-8619-c84b8f3e4350,6253e25d-beb4-4bc9-9b42-d26f52547aeb,7df84b53-1c74-435b-a30d-3ee30f0c92b4,d7052ffb-7395-4c43-9286-719772758174,e36dbe84-f60a-45a3-b572-2120bd789a36'
        }
      },
      payload: {
        multipart: true,
        impersonation_voice: 'voice',
        'Transfer-Encoding': 'chunked'
      }
    )
   rescue RestClient::ExceptionWithResponse => e
    byebug
    @result = Result.create(result_params)
    render json: { url: target_result_url(@result.target_id, @result.id) }
end
```

## エラーから考えられる原因

postmanでは正常に動いていることからも、rest-clientでのリクエストボディへの音声ファイルの指定方法が間違っているのではないか？と考えております。

※過去に今回と同様のエラーがpostman上で発生したことがあり、その際はファイルサイズの問題ではなく、ほとんど無音の音声ファイルを添付していたことが原因でした。

### 別のWAVファイルを指定

録音画面で生成している音声ファイルに問題があるのかと思い、別のwavファイルで試しました。
下記のように変更し、既にpostman上でレスポンス取得に成功しているファイルを使いましたが、同様のエラーでした。
voice = File.new(params[:impersonation_voice])　→　voice = Target.find(7).target_voice.url

### ファイルのサイズを再確認

postman上で成功していたwavファイルの詳細を確認したところ、「44.1 kHz、16bit、Stereo」でした。
postmanではファイルのサイズに関係なく動いていたことから、今回のエラーはただのファイルサイズの問題ではないと考えています。

### エラーメッセージ通りのファイルサイズに変更

念の為、「16Khz、16bit、Mono」に変更したwavファイルをテスト用に作成し、voiceに指定しましたが、同様のエラーでした。

### **Content-typeの記載を変更**

'Content-type': 'audio/wav; codecs=audio/pcm; samplerate=16000',の追加。

### 参考にしたURL

[[GitHub - rest-client/rest-client: Simple HTTP and REST client for Ruby, inspired by microframework syntax for specifying actions.](https://github.com/rest-client/rest-client#exceptions-see-httpwwww3orgprotocolsrfc2616rfc2616-sec10html)[](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/387)](https://github.com/rest-client/rest-client#exceptions-see-httpwwww3orgprotocolsrfc2616rfc2616-sec10html)

[https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/387](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/387)

[[Text Independent - Create Profile - REST API (Azure Speaker Recognition)](https://docs.microsoft.com/ja-jp/rest/api/speakerrecognition/identification/text-independent/create-profile)](https://docs.microsoft.com/ja-jp/rest/api/speakerrecognition/identification/text-independent/create-profile)

[[cognitive-services-quickstart-code/speaker-recognition.sh at master · Azure-Samples/cognitive-services-quickstart-code](https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/curl/speech/speaker-recognition.sh)](https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/curl/speech/speaker-recognition.sh)

**Comment by MrFuku** [comment]
こっちのやり方を試してください！
https://github.com/rest-client/rest-client#multipart

**Comment by beppumasaki** [comment]
コメント頂き、ありがとうございます！
頂いたURLを参考にしましたが、「RestClient.postを使った場合に、①ファイルの送信と②パラメータを渡すことを同時に行う方法」がわかりませんでした。
その後調べていくうちに、今回のようにファイル送信の際にクエリパラメータを渡す必要がある場合では、RestClient::Requestを使った方が良いとの記事を見つけたので、下記のように実装しました。
※File.newの引数も、頂いたURLを参考に変更してみました。

### 現在のコード

```jsx
def create
    request = RestClient::Request.new(
      method: :post,
      url: 'https://westus.api.cognitive.microsoft.com/speaker/identification/v2.0/text-independent/profiles/identifySingleSpeaker',
      headers: {
        'Ocp-Apim-Subscription-Key': 'd707afb0596c47968b5e0ed7f263c9be',
        'Content-type': 'audio/wav; codecs=audio/pcm; samplerate=16000',
        params: {
          profileIds: '42408f55-0250-4679-9950-ab72672f3958,305fbca2-be86-49b9-8619-c84b8f3e4350,6253e25d-beb4-4bc9-9b42-d26f52547aeb,7df84b53-1c74-435b-a30d-3ee30f0c92b4,d7052ffb-7395-4c43-9286-719772758174,e36dbe84-f60a-45a3-b572-2120bd789a36'
        }
      },
      payload: {
        multipart: true,
        impersonation_voice: File.new("/Users/beppumasaki/workspace/my_app/impersonation_practice/public/uploads/result/impersonation_voice/19/voice.wav",'rb'),
        'Transfer-Encoding': 'chunked',
      })

     @result = Result.create(result_params)
     render json: { url: target_result_url(@result.target_id, @result.id) }
  end
```



現在のコードでデバッグすると、下記の画像のように400 Bad Requestとなっております。

![https://i.gyazo.com/80b92a1f08153d1d588180db6f6d602e.png](https://i.gyazo.com/80b92a1f08153d1d588180db6f6d602e.png)



また、エラーメッセージの詳細を確認したところ、下記のようになっておりました。
"{\"error\":{\"code\":\"BadRequest\",\"message\":\"Audio format not supported\"}}”

### エラーから考えられる原因

request.payloadの結果から、wavファイルに変換されていないのでないか？と考え、念の為payloadにcontent_type: 'audio/wav’を渡して検証しましたが、結果は変わりませんでした。

### 参考にしたURL

[[Ruby rest-client file upload as multipart form data with basic authenticaion](https://stackoverflow.com/questions/11388090/ruby-rest-client-file-upload-as-multipart-form-data-with-basic-authenticaion)](https://stackoverflow.com/questions/11388090/ruby-rest-client-file-upload-as-multipart-form-data-with-basic-authenticaion)

[[Rubyのrest-clientを使ってmultipart/form-dataでファイルアップロードする](https://daipresents.com/2017/03/23/ruby-rest-client-upload/)](https://daipresents.com/2017/03/23/ruby-rest-client-upload/)

**Comment by MrFuku** [comment]
400エラーということはリクエストは遅れているんですよね？
その際のbodyやheaderはどうなっていますか？

またリクエストの指定の仕方に誤りがなかったかもう一度確認してください
ぱっと見「Transfer-Encodingをpayloadに指定している点」や「headersに」

**Comment by beppumasaki** [comment]
payloadに渡すデータを下記のように変更したところ、うまくいきました。
ハッシュ形式で渡してしまっていたのが原因でした。

```jsx
request = RestClient::Request.new(
      method: :post,
      url: 'https://westus.api.cognitive.microsoft.com/speaker/identification/v2.0/text-independent/profiles/identifySingleSpeaker',
      headers: {
        'Ocp-Apim-Subscription-Key': 'd707afb0596c47968b5e0ed7f263c9be',
        'Content-type': 'audio/wav; codecs=audio/pcm; samplerate=16000',
        'Transfer-Encoding': 'chunked',
        params: {
          profileIds: '42408f55-0250-4679-9950-ab72672f3958,305fbca2-be86-49b9-8619-c84b8f3e4350,6253e25d-beb4-4bc9-9b42-d26f52547aeb,7df84b53-1c74-435b-a30d-3ee30f0c92b4,d7052ffb-7395-4c43-9286-719772758174,e36dbe84-f60a-45a3-b572-2120bd789a36'
        }
      },
      payload: File.new("/Users/beppumasaki/workspace/my_app/impersonation_practice/public/uploads/result/impersonation_voice/19/voice.wav",'rb')
    )
    response  = request.execute
    # rescue RestClient::ExceptionWithResponse => e
    byebug
```

実際にpayloadを調べると、wavファイルになっておりました。

![https://i.gyazo.com/d7d6a261fac4154155e190b0fa982d4d.png](https://i.gyazo.com/d7d6a261fac4154155e190b0fa982d4d.png)

ご対応頂き、誠にありがとうございました。
